### Successful Responses

### Retrieve All Alcohol from Alcohol Table

GET http://localhost:3000/api/mixers


### Add new Alcohol

POST http://localhost:3000/api/mixers
Content-Type: application/json
# Use the User http client to log in with a user, then get the jwt tokent and paste it here in the format of "Bearer <jwt token>"
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDMxMDU2OTMsInN1YiI6NH0.Z2lg5BPc9ikddcYmUHrjuxWIC6XjqgOHJnSdi_KiN9U

{
    "name":"Pepsi",
    "volume_in_ml": 4000,
    "critical_volume":2000

}


### Edit an Existing Alcohol

PUT http://localhost:3000/api/mixers/6
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDMxMDU2OTMsInN1YiI6NH0.Z2lg5BPc9ikddcYmUHrjuxWIC6XjqgOHJnSdi_KiN9U

{
    "name":"Cola",
    "volume_in_ml": 4000,
    "critical_volume":2000

}